### ISSUE TITLE
crashes in meteorpad

### ISSUE THREAD

**Issue by Maxhodges** [JackAdams/constellation-distro#1]
Your app is crashing. Here's the latest log.

=> Errors prevented startup:

While building the application:
error: no such package: 'babrahams'
error: no such package: 'constellation'
error: no such package: 'lai'
error: no such package:

**Comment by JackAdams** [comment]
By the look of those errors, something went wrong in Meteorpad.  Just now I added `babrahams:constellation` to a fresh Leaderboard app and it all worked fine.
