### ISSUE TITLE
bundled packages production size

### ISSUE THREAD

**Issue by avalanche1** [JackAdams/constellation-distro#5]
Hi!
So when installing your package, I also receive these as dependencies
![image](https://cloud.githubusercontent.com/assets/10534563/10692997/43e8bbde-79a6-11e5-9902-992b02702e29.png)
I guess, some of them goes to production? If so - how do they increase total size of production app?

**Comment by JackAdams** [comment]
None of them go to production. That's the beauty of a debugOnly package.

**Comment by avalanche1** [comment]
nice!

**Comment by avalanche1** [comment]
So, do they all receive debugOnly flag of their 'parent' pakcage?

**Comment by JackAdams** [comment]
I believe that's the case.

For the record, of those 16 packages listed, 10 actually have the `debugOnly=true` flag explicitly in their `package.js`, but I think (in fact, I'm pretty sure) the build tool won't include dependencies of debugOnly packages unless they are included by other non-debugOnly packages or as top-level dependencies of the app.
