### ISSUE TITLE
Adding constellation breaks app

### ISSUE THREAD

**Issue by derwaldgeist** [JackAdams/constellation-distro#7]
When I add the `babrahams:constellation` package to my app, it won't run anymore (no template is being rendered). In the browser console, I only see these two messages:

``` js
Uncaught Error: EJSON.parse argument should be a string
EJSON.parse @ ejson.js:347
_psGet @ persistent_session.js:63
(anonymous function) @ persistent_session.js:244
runStartupCallbacks @ startup_client.js:30
ready @ startup_client.js:32

Uncaught Error: EJSON.parse argument should be a string
EJSON.parse @ ejson.js:347
_psGet @ persistent_session.js:63
_psSetDefault @ persistent_session.js:187
_psSetDefaultPersistent @ persistent_session.js:199
(anonymous function) @ lai-ddp-inspector.js:207
runStartupCallbacks @ startup_client.js:30
ready @ startup_client.js:32
```

**Comment by JackAdams** [comment]
Sounds like #3 again.

First, `meteor remove babrahams:constellation`, then `meteor add` these one at a time:

```
constellation:console
babrahams:temple
constellation:subscriptions
constellation:session
constellation:autopublish
constellation:tiny
constellation:position
lai:ddp-inspector
constellation:plugins
```

(I think that adding `lai:ddp-inspector` is going to be the package that causes the error, as that's the one with the dependency on `u2622:persistent-session`.)

**Comment by derwaldgeist** [comment]
Confirmed. The problem occurred after installing `lai:ddp-inspector`. So I'm closing this as a dup of #6.

**Comment by derwaldgeist** [comment]
BTW: Adding constellation:plugins doesn't work either, I'm getting the following errors:

```
While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: ecmascript 0.1.3-plugins.1

unknown package: isobuild:isopack-2
Required by: constellation:plugins 0.1.1
```

**Comment by JackAdams** [comment]
Thanks for reporting this. I didn't know about that. Will look into it.

**Comment by derwaldgeist** [comment]
Thanks. I think it is related to my use of Meteor 1.1, as the packages are not available in this version.

**Comment by JackAdams** [comment]
Sorry. That's me being stupid and putting unnecessarily high version dependencies on the constellation package so. They should all be compatible with 1.0. I'll fix that in the next minor release - about a week away.

**Comment by derwaldgeist** [comment]
Fine, thanks!

**Comment by JackAdams** [comment]
Sorry, I forgot to get back to you about this.  I think 1.3.0 has all the dependencies back down to 1.0.  Hope it works now.
Brent

**Comment by derwaldgeist** [comment]
Thanks for letting me know! Will try it.
